{% set name = "manim" %}
{% set version = "0.16.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/manim-{{ version }}.tar.gz
  sha256: ff91a7e385ae258c9322d15b5e18c27ec5e91c634da85af70ab6f5ab83053d6e

build:
  noarch: python
  entry_points:
    - manim = manim.__main__:main
    - manimce = manim.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - poetry >=1.0.10
    - poetry-core
  run:
    - click >=7.2
    - click-default-group >=1.2.2
    - cloup >=0.13.0
    - colour >=0.1.5
    - decorator >=5.0.7
    - isosurfaces ==0.1.0
    - manimpango >=0.4.0.post0
    - mapbox_earcut >=0.12.10
    - moderngl >=5.6.3
    - moderngl-window >=2.3.0
    - networkx >=2.5
    - numpy >=1.19
    - pillow >=9.1
    - pycairo >=1.19
    - pydub >=0.25.1
    - pygments >=2.10.0
    - python >=3.8
    - requests >=2.26.0
    - rich >=6.0,!=12.0.0
    - scipy >=1.7.3
    - screeninfo >=0.8
    - skia-pathops >=0.7.0
    - srt >=3.5.0
    - tqdm >=4.62.3
    - watchdog >=2.1.6
    - ffmpeg

test:
  imports:
    - manim
  commands:
    - pip check
    - manim --help
    - manimce --help
  requires:
    - pip

about:
  home: https://www.manim.community/
  summary: Animation engine for explanatory math videos.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - naveen521kk
    - pavelzw
