{% set name = "manim" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/manim-{{ version }}.tar.gz
  sha256: 748115ffc1dea24940fd6d7a3edcae0ccedc3e1874ebc1f5d7e5c6d69a4f4505

build:
  noarch: python
  entry_points:
    - manim = manim.__main__:main
    - manimce = manim.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry >=1.0.10
    - poetry-core
  run:
    - av >=9.0.0,<14.0.0
    - beautifulsoup4 >=4.12
    - typing_extensions >=4.0.0
    - importlib-metadata >=3.6
    - click >=8.0
    - click-default-group >=1.2.2,<2.0.0
    - cloup >=2.0.0
    - decorator >=4.3.2
    - isosurfaces >=0.1.0
    - manimpango >=0.5.0,<1.0.0
    - mapbox_earcut >=1.0.0
    - moderngl >=5.0.0,<6.0.0
    - moderngl-window >=2.0.0
    - networkx >=2.6
    - numpy >=1.26
    - pillow >=9.1
    - pycairo >=1.13,<2.0.0
    - pydub >=0.20.0
    - pygments >=2.0.0
    - python >={{ python_min }}
    - requests >=2.26.0,<3.0.0
    - rich >=12.0.0
    - scipy >=1.13.0
    - screeninfo >=0.7
    - skia-pathops >=0.7.0
    - srt >=3.0.0
    - svgelements >=1.8.0
    - tqdm >=4.0.0
    - typing-extensions >=4.0.0
    - watchdog >=2.0.0
    - ffmpeg

test:
  imports:
    - manim
  commands:
    - pip check
    - manim --help
    - manimce --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.manim.community/
  summary: Animation engine for explanatory math videos.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - naveen521kk
    - pavelzw
