context:
  name: manim
  version: 0.21.0
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 2f3d719e726c9abf49b1bea503fb17510ee2063dab53915ab44a2c47c32f9a13

build:
  noarch: python
  python:
    entry_points:
      - manim = manim.__main__:main
      - manimce = manim.__main__:main
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build >=0.12.1,<0.13.0
  run:
    - python >=${{ python_min }}
    - av >=15.0
    - click >=8.0
    - cloup >=2.0.0
    - decorator >=4.3.2
    - isosurfaces >=0.1.1
    - manimpango >=0.6.1,<1.0.0
    - mapbox_earcut >=1.0.0
    - moderngl >=5.7.0,<6.0.0
    - moderngl-window >=2.0.0
    - networkx >=2.6
    - numpy >=2.1
    - pillow >=11.0
    - pycairo >=1.14,<2.0.0
    - pydub >=0.22.0
    - pygments >=2.17
    - rich >=12.0.0
    - scipy >=1.15.0
    - screeninfo >=0.7.0
    - skia-pathops >=0.9.0
    - srt >=3.0.0
    - svgelements >=1.9.0
    - tqdm >=4.21.0
    - beautifulsoup4 >=4.12
    - watchdog >=2.0.0
    - audioop-lts >=0.2.1
    - typing_extensions >=4.12.0
    - ffmpeg
  run_constraints:
    - typst-py >=0.14.0
    - notebook >=7.3.2
    - jupyterlab >=4.3.4
tests:
  - python:
      pip_check: true
      imports:
        - manim
      python_version: ${{ python_min }}.*
  - script:
      - manim --help
      - manimce --help

about:
  homepage: https://manim.community
  summary: Animation engine for explanatory math videos.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/ManimCommunity/manim

extra:
  recipe-maintainers:
    - naveen521kk
    - pavelzw
